name=input("enter ur name")
city=input("enter ur city")
fav_food=input("enter ur fav food")
fav_game=input("enter ur fav game")
fav_player=input("enter ur fav player")
fav_movie=input("enter ur fav movie")
fav_actor=input("enter ur fav actor")
fav_actress=input("enter ur fav actress")
fav_author=input("enter ur fav author")
fav_song=input("enter ur fav song")

print("!!!!info!!!!")
print(f'{name=}')
print(f'{city=}')
print(f'{fav_food=}')
print(f'{fav_game=}')
print(f'{fav_player=}')
print(f'{fav_movie=}')
print(f'{fav_actor=}')
print(f'{fav_actress=}')
print(f'{fav_author=}')
print(f'{fav_song=}')
